run:
  timeout: 5m
  go: '1.24'

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unused
    - gosimple
    - staticcheck
    - typecheck
    - goconst
    - gocyclo
    - revive

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/tommyorndorff/operata-events
  goconst:
    min-len: 2
    min-occurrences: 3
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: exported
        disabled: false
      - name: unexported-return
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - goconst
